DEP-3637 Close CJRS/SEISS DEP pages
hmrc/digital-engagement-platform-frontend pull request #439
Opened 2022-07-28 13:57 UTC by AdamSmithHMRC

# DEP-(StoryNumberHere)

## Checklist PR Raiser
 - [ ]  I've ensured code coverage has not decreased
 - [ ]  I've dealt with any new compilation warnings
 - [ ]  I've ensured the team's coding standards have been met (TBC)?
 - [ ]  If relevant, I've created corresponding app-config-XXX changes?
 - [ ]  If I've created new test data, I've ensured there is no real person's data (see https://confluence.tools.tax.service.gov.uk/display/CD/Test+Data+in+the+Open) 
 - [ ]  I've considered the impact my changes have on the UI/Journey tests (please do not break them)
-  [ ]  If relevant, I've added links to associated PRs

## Checklist PR Reviewer
 - [ ]  I've checked to ensure all relevant unit tests have been written
 - [ ]  I've checked to ensure the team's coding standards have been met
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
 - [ ]  If I merge I will ensure I use squash and merge

2022-07-28 13:59 UTC, AdamSmithHMRC commented
Waiting for confirmation of removal of DA links from the COVID from [SASS-2953](https://jira.tools.tax.service.gov.uk/browse/DEP-2953)

2022-08-09 10:00 UTC, tonymyers requested changes

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/JobRetentionSchemeView.scala.html
> -        <a class="govuk-link" id="return-link" href="@appConfig.jobRetentionSchemeReturnUrl">
I don't think the jobRetentionSchemeReturnUrl in app.config is used anywhere else. Can you please check and remove from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/JobRetentionSchemeView.scala.html
> -            <a class="govuk-link" id="report-fraud-link" href="@appConfig.reportFraudulentActivityUrl">
I don't think the checkCoveredByCoronavirusJRSUrl in app.config is used anywhere else. Can you please check and remove from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/JobRetentionSchemeView.scala.html
> -            <a class="govuk-link" id="check-jrs-scheme-link" href="@appConfig.checkCoveredByCoronavirusJRSUrl">
I don't think the checkCoveredByCoronavirusJRSUrl in app.config is used anywhere else. Can you please check and remove from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/va/VASupportForCoronavirusView.scala.html
> -            <a class="govuk-link" id="coronavirus-general-info-link" href="@appConfig.coronavirusGeneralInfoUrl">@messages("support.for.coronavirus.linkto.general.info")</a>
I don't think the coronavirusGeneralInfoUrl in app.config is used anywhere else. Can you please check and remove  from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/va/VASelfEmploymentIncomeSupportSchemeView.scala.html
> -        <a class="govuk-link" id="self-employment-income-support-scheme-link" href="@appConfig.selfEmploymentIncomeSupportReturnUrl">@messages("self-employment-income-support.li1")</a>
I don't think the selfEmploymentIncomeSupportReturnUrl in app.config is used anywhere else. Can you please check and remove from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/SelfEmploymentIncomeSupportView.scala.html
> -        <a class="govuk-link" id="return-link" href=@appConfig.selfEmploymentIncomeSupportReturnUrl>
I don't think the selfEmploymentIncomeSupportReturnUrl in app.config is used anywhere else. Can you please check and remove from appconfig if required

2022-08-09 10:00 UTC, tonymyers commented on app/views/va/VASupportForCoronavirusView.scala.html
> -    <h1 class="header-margin-top">@messages("va.global.h1.title")</h1>
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 10:00 UTC, tonymyers commented on app/views/va/VASelfEmploymentIncomeSupportSchemeView.scala.html
> -@main_template(title = messages("va.global.h1.title"), navTitle = Some(messages("global.nav.va.title"))) {
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 10:00 UTC, tonymyers commented on app/views/CUIViews/JobRetentionSchemeHelpView.scala.html
> -    title = messages("cui.job.retention.scheme.title"),
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/JobRetentionSchemeView.scala.html
> -@main_template(title = messages("job.retention.scheme.title")) {
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/JobRetentionSchemeView.scala.html
> -    <h1 class="header-margin-top">@messages("job.retention.scheme.title")</h1>
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 10:00 UTC, tonymyers commented on app/views/webchat/SelfEmploymentIncomeSupportView.scala.html
> -@main_template(title = messages("self.employment.income.support.scheme.title")) {
You need to remove any messages from the message file that are used on this page but not used anywhere else

2022-08-09 16:07 UTC, tonymyers approved these changes

2022-08-15 08:42 UTC, tonymyers approved these changes

2022-08-15 08:45 UTC, tonymyers approved these changes

2022-08-15 08:45 UTC, merged